# Generated by Django 2.2.10 on 2021-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210512_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.CharField(blank=True, default='xx/xx/xxxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='hit_percentage',
            field=models.CharField(blank=True, default='0%', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='order_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='order_type',
            field=models.CharField(blank=True, default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(blank=True, default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_address',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_hits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
